#!/bin/bash

{
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": ":dollar::moneybag: *GUAP MASTERNODE REPORT - JL - * :moneybag::dollar:\nReport for server '"$server"'; owner Jason Lamb."
			}
		},
		{
			"type": "context",
			"elements": [
				{
					"type": "mrkdwn",
					"text": "Please see below a snapshot of your masternodes. See also included below links for your masternodes where you can view their recent transaction activity on the GUAP Blockchain Explorer. "
				}
			]
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "<!date^'"$d"'^Posted {date_num} {time_secs}|Posted '"$d_formatted"'>"
			}
		},
		{
			"type": "divider"
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*Label*            *GUAP Address*                                                                    *Subtotal* '"$MNs_data"'\n\n"
			}
		},
		{
			"type": "divider"
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*Total Current GUAP Holdings*                                                                 *'"$MN_Total"'*\n*Total Current GUAP Holdings (USD)*                                                      *\$'"$GuapUSD"'"
			}
		},
		{
			"type": "divider"
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "\nLast report was generated on '"$LastGuapTime_var"' \nGUAP earned since last report: '"$GUAPearned"'[\$'"$GUAPearnedUSD"'] in last '"$TimeElapsed"' \nEarn rate: '"$GUAPearnRateH"'/hour '"$GUAPearnRateM"'/min '"$GUAPearnRateS"'/sec \nEarn rate(\$): '"$GUAPUSDearnRateH"'/hour '"$GUAPUSDearnRateM"'/min '"$GUAPUSDearnRateS"'/sec"
			}
		},
		{
			"type": "divider"
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*GUAP Stats* \nTotal GUAP Money Supply                                                                      '"$GUAPTotal"' \nTotal GUAP Money Supply (USD)                                                           \$'"$GuapTotalUSD"' \nCurrent per GUAP Value (USD)                                                               \$'"$GUAPValue"' \nPercentage of total GUAP Money Supply held here                             '"$Perc"'% \nTotal number of GUAP masternodes                                                      '"$MNCount"' \nPercentage of total GUAP voting power represented here                  '"$Perc2"'% \nGUAP Chain Block Count                                                                        '"$BlockHeight"'"
			}
		},
		{
			"type": "divider"
		},
		{
			"type": "context",
			"elements": [
				{
					"type": "mrkdwn",
					"text": "*Note:* Report automatically generated by masternode monitoring system.\nPlease message <@U013QSJTGEA> for more information."
				}
			]
		},
		{
			"type": "divider"
		},
		{
			"type": "divider"
		}
	]
}
